dnl# check system characteristics:
AC_DEFUN([gl_SYSTEM_SPECIFIC_MACROS],[
  AC_REQUIRE([AC_CANONICAL_TARGET])dnl
  AC_REQUIRE([gl_USE_SYSTEM_EXTENSIONS])dnl
  AC_REQUIRE([gl_DOUBLE_SLASH_ROOT])dnl
  AC_REQUIRE([gl_PATHMAX])dnl
  AC_REQUIRE([AC_EXEEXT])dnl
  AC_REQUIRE([AC_OBJEXT])dnl
  AC_REQUIRE([AC_SYS_INTERPRETER])dnl
  AC_REQUIRE([AC_SYS_LONG_FILE_NAMES])dnl
])dnl
